// import { Geist, Geist_Mono } from "next/font/google";
import { Archivo, Freeman } from "next/font/google";
import "./global.css";
import Navbar from "@/components/Navbar";
import { Toaster } from "react-hot-toast";
import { ContextProvider } from "./contex/context";

const freeman = Freeman({
  subsets: ["latin"],
  weight: ["400"],
  display: "swap",
});

export const metadata = {
  title: "Dictionary by Divyesh",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${freeman.className} antialiased w-[90vw] mx-auto scrollbar bg-[url('/bg.jpg')]  bg-cover`}
      >
        <Toaster />
        <ContextProvider>
          {" "}
          <Navbar />
          {children}
        </ContextProvider>
      </body>
    </html>
  );
}
